spring.application.name=eventop
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/eventop_db
spring.datasource.username=eventop_user
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
