spring.application.name=Eventop

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/eventop_db
spring.datasource.username=postgres
spring.datasource.password=password

# Tamanio maximo del pool
spring.datasource.hikari.maximum-pool-size=5
# Numero minimo de conexiones inactivas.
spring.datasource.hikari.minimum-idle=5
# Tiempo maximo en milisegundos que el cliente esperara por una conexion del pool
spring.datasource.hikari.connection-timeout=30000
# Tiempo maximo que una conexion puede permanecer inactiva antes de ser cerrada
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.connection-test-query=SELECT 1
spring.datasource.driver-class-name=org.postgresql.Driver


#logging.level.com.zaxxer.hikari.HikariConfig=DEBUG
#logging.level.com.zaxxer.hikari=DEBUG

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

# SEGURIDAD
# Parametros de seguridad
security.jwt.token.secret-key=n70iaIlY02WbW61O09zJ8WiAvcZ+i/qZZKEyRlD5ovg=
# Tiempo de expiracion del JWT en minutos
security.jwt.token.expire-length=480

#Parametros de conexion al Sistema 1
sistema1.url-base=http://172.16.76.144:8081
sistema1.connect-timeout=1000
sistema1.read-timeout=2000
